# Generated by Django 5.1.4 on 2024-12-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_amassscan_whoislookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
            ],
        ),
    ]
