# Generated by Django 5.1.4 on 2024-12-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_domain_toolresult_delete_toollog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolresult',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='ToolResult',
        ),
    ]
