# Generated by Django 5.1.4 on 2024-12-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_toolresult_domain_delete_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresult',
            old_name='scanned_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='target',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='tool_name',
            field=models.CharField(max_length=100),
        ),
    ]
