# Generated by Django 5.1.4 on 2024-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_rename_scanned_at_scanresult_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('port_scanner', 'Port Scanner'), ('whois', 'Whois Lookup'), ('domain_finder', 'Domain Finder'), ('subdomain_finder', 'Subdomain Finder'), ('zap', 'ZAP'), ('website_scanner', 'Website Scanner')], help_text='Type of scan performed.', max_length=100)),
                ('target', models.CharField(help_text='The target domain, IP, or URL of the scan.', max_length=255)),
                ('result', models.TextField(help_text='The raw result of the scan.')),
                ('status', models.CharField(choices=[('running', 'Running'), ('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', help_text='The current status of the scan.', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time when the scan was initiated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time when the scan was last updated.')),
                ('created_by', models.CharField(blank=True, help_text='The user who initiated the scan.', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Scan Report',
                'verbose_name_plural': 'Scan Reports',
                'ordering': ['-timestamp'],
            },
        ),
    ]
