# Generated by Django 5.1.4 on 2024-12-31 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_host_finding_port_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('quick', 'Quick Scan'), ('advanced', 'Advanced Scan'), ('custom', 'Custom Scan')], default='quick', help_text='The scan profile used.', max_length=50)),
                ('target', models.URLField(help_text='Target URL for the scan.')),
                ('options', models.JSONField(help_text='JSON storing all scan options, e.g., XSS, SQLMap, custom rules.')),
                ('hidden_params', models.BooleanField(default=False, help_text='Enable brute-forcing hidden parameters.')),
                ('tamper_scripts', models.JSONField(blank=True, help_text='List of tamper scripts for WAF bypass (e.g., space2comment).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created the scan configuration.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AmassScan',
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
        migrations.DeleteModel(
            name='WhoisLookup',
        ),
        migrations.AddField(
            model_name='finding',
            name='proof_of_concept',
            field=models.TextField(blank=True, help_text='Details or payload used for exploitation.', null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='vulnerability_type',
            field=models.CharField(choices=[('csrf', 'Cross-Site Request Forgery (CSRF)'), ('xss', 'Cross-Site Scripting (XSS)'), ('sqli', 'SQL Injection (SQLi)'), ('lfi', 'Local File Inclusion (LFI)'), ('rfi', 'Remote File Inclusion (RFI)'), ('open_redirect', 'Open Redirect'), ('sensitive_data', 'Sensitive Data Exposure')], default='info', help_text='The type of vulnerability identified.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='export_path',
            field=models.CharField(blank=True, help_text='Path to the exported report file.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='severity_summary',
            field=models.JSONField(blank=True, help_text='Summary of vulnerabilities grouped by severity levels (Critical, High, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='scan_config',
            field=models.ForeignKey(blank=True, help_text='Configuration used for the scan.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.scanconfig'),
        ),
    ]
