# Generated by Django 5.1.4 on 2025-01-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_scanconfig_delete_amassscan_delete_scanresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress percentage of the scan.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', help_text='The current status of the scan.', max_length=50),
        ),
    ]
