# Generated by Django 5.1.4 on 2025-01-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_report_progress_alter_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='scan_type',
        ),
    ]
