# Generated by Django 5.1.4 on 2025-01-04 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_remove_report_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='scan_type',
            field=models.CharField(choices=[('port_scanner', 'Port Scanner'), ('domain_finder', 'Domain Finder'), ('subdomain_finder', 'Subdomain Finder'), ('website_scanner', 'Website Scanner'), ('whois_lookup', 'Whois Lookup'), ('dns_lookup', 'DNS Lookup')], default=django.utils.timezone.now, help_text='Type of scan performed.', max_length=100),
            preserve_default=False,
        ),
    ]
