# Generated by Django 5.1.4 on 2025-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_report_scan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scan Report', 'verbose_name_plural': 'Scan Reports'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.CharField(blank=True, help_text='The user who initiated the scan.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result',
            field=models.TextField(blank=True, help_text='The raw result of the scan.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity_summary',
            field=models.JSONField(blank=True, help_text='Summary of vulnerabilities grouped by severity levels.', null=True),
        ),
    ]
