# Generated by Django 5.1.4 on 2025-01-25 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_alter_report_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportWebsiteScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=100)),
                ('target', models.URLField()),
                ('status', models.CharField(max_length=100)),
                ('progress', models.IntegerField(default=0)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
